name: banky
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  percent_indicator: ^4.0.0
  syncfusion_flutter_charts: ^19.4.53
  change_app_package_name: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: 'bold'
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: 'semi-bold'
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf
    - family: 'medium'
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
    - family: 'regular'
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
  
