name: parkme
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.1.2
  flutter_credit_card: ^3.0.1
  percent_indicator: ^4.0.0
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  fonts:
     - family: 'bold'
       fonts:
         - asset: assets/fonts/Roboto-Bold.ttf     
     - family: 'medium'
       fonts:
         - asset: assets/fonts/Roboto-Medium.ttf
     - family: 'regular'
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
