name: shop2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon/
  

  fonts:
     - family: 'bold'
       fonts:
         - asset: assets/fonts/Jost-Bold.ttf     
     - family: 'medium'
       fonts:
         - asset: assets/fonts/Jost-Medium.ttf
     - family: 'regular'
       fonts:
         - asset: assets/fonts/Jost-Regular.ttf

  


    

