name: food2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  carousel_slider: ^2.3.1
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  timelines: ^0.1.0
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/process/

  fonts:
    - family: 'bold'
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: 'medium'
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: 'regular'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: 'semibold'
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
