name: social_network
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  percent_indicator: ^4.0.0
  flutter_staggered_grid_view: ^0.6.1
  tcard: ^1.3.5
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  fonts:
     - family: 'bold'
       fonts:
         - asset: assets/fonts/Roboto-Bold.ttf     
     - family: 'medium'
       fonts:
         - asset: assets/fonts/Roboto-Medium.ttf
     - family: 'regular'
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
